### ISSUE TITLE
make it searchable

### ISSUE THREAD

**Issue by redragonx** [TheFixers/node-honeypot-client#3]
by ports, by dates, etc

**Comment by rabbitfighter81** [comment]
This is how searches are done on the front-end:They aren't... What will have to happen is that you do the search on the back-end and there's a search endpoint exposed such as 999.99.99://myApp/seacrh=searchTerm that I send an ajax request to and get a json response of the term. Otherwise the front-end will violate MVC and FLUX patterns. It could be done, I'm just sayin...

**Comment by joshcalafell** [comment]
Done. Need to change css of search to make red background on result highlighting...
